#!/bin/bash

# Railway Deployment Debugging Script

echo "=== RAILWAY DEPLOYMENT DEBUG ==="
echo ""

echo "Step 1: CHECK CURRENT CODE DEPLOYED"
echo "Buka Railway → Booking Service → Deployments"
echo "Lihat apakah commit '9ee0e88' sudah ter-deploy?"
echo "Kalau belum, klik 'New Deployment' → 'Redeploy'"
echo ""

echo "Step 2: CHECK ENVIRONMENT VARIABLES"
echo "Buka Railway → Booking Service → Variables tab"
echo ""
echo "REQUIRED VARIABLES:"
echo "1. DATABASE_URL atau DB_HOST"
echo ""
echo "Cara SET (PILIH SALAH SATU):"
echo ""
echo "OPTION A - Reference (RECOMMENDED):"
echo "  1. Klik 'New Variable'"
echo "  2. Klik icon Reference (🔗)"
echo "  3. Pilih PostgreSQL service"
echo "  4. Railway akan auto-set DATABASE_URL ✅"
echo ""
echo "OPTION B - Manual:"
echo "  Buka PostgreSQL service → Variables tab"
echo "  Copy values dan buat variables di Booking Service:"
echo "  - DB_HOST = <value dari PGHOST>"
echo "  - DB_PORT = 5432"
echo "  - DB_USER = <value dari PGUSER>"
echo "  - DB_PASSWORD = <value dari PGPASSWORD>"
echo "  - DB_NAME = <value dari PGDATABASE>"
echo ""

echo "Step 3: VERIFY ENV VARS ARE SET"
echo "Buka Railway → Booking Service → View Logs"
echo "Cari log seperti:"
echo "  - DATABASE_URL=postgres://..."
echo "  ATAU DB_HOST=..."
echo ""

echo "Step 4: TRIGGER NEW DEPLOYMENT"
echo "Setelah set env vars:"
echo "  1. Railway → Booking Service"
echo "  2. Klik 'New Deployment'"
echo "  3. Pilih 'Rebuild without cache'"
echo "  4. Tunggu deployment selesai"
echo ""

echo "Step 5: TEST HEALTH CHECK"
echo "Setelah deployment selesai:"
echo "  curl https://<booking-service-railway-url>/health"
echo ""

echo "=== MASALAH UMUM ==="
echo ""
echo "❌ Error: ENOTFOUND postgres"
echo "   Artinya: DB_HOST masih 'postgres' (default)"
echo "   Fix: Set DATABASE_URL atau DB_HOST di Railway Variables"
echo ""
echo "❌ Error: connection refused"
echo "   Artinya: DB_HOST salah atau PostgreSQL belum ready"
echo "   Fix: Cek env vars dan pastikan PostgreSQL service running"
echo ""
echo "❌ Error: authentication failed"
echo "   Artinya: DB_USER atau DB_PASSWORD salah"
echo "   Fix: Copy values yang benar dari PostgreSQL service"
echo ""

echo "=== NEED HELP? ==="
echo "Screenshot:"
echo "1. Railway → Booking Service → Variables tab"
echo "2. Railway → Booking Service → Deployments tab"
echo "3. Railway → Booking Service → View Logs"
echo ""
echo "Share screenshots agar bisa membantu debug! 🚀"
